version: "3.7"
services:
  timemachine:
    network_mode: "host"
    environment:
      - CUSTOM_SMB_CONF=false
      - CUSTOM_USER=false
      - LOG_LEVEL=info
      - EXTERNAL_CONF=
      - HIDE_SHARES=no
      - MIMIC_MODEL=TimeCapsule8,119
      - TM_USER=timemachine
      - TM_GROUPNAME=timemachine
      - TM_UID=1000
      - TM_GID=1000
      - PASSWORD=timemachine
      - SET_PERMISSIONS=false
      - SHARE_NAME=TimeMachine
      - SMB_PORT=445
      - VOLUME_SIZE_LIMIT=0
      - WORKGROUP=WORKGROUP
    restart: unless-stopped
    ports:
     - "137:137/udp"
     - "138:138/udp"
     - "139:139"
    volumes:
     - /path/to/your/timemachine/volume:/opt/timemachine
     - timemachine-var-lib-samba:/var/lib/samba
     - timemachine-var-cache-samba:/var/cache/samba
     - timemachine-run-samba:/run/samba
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    container_name: timemachine
    image: tom20mcd/timemachine-rpi
